// examples/lit/src/components/Heading.ts
import { ShallowLitElement, useNodeViewContext } from '@prosemirror-adapter/lit'
import { customElement } from 'lit/decorators.js'
import { ref } from 'lit/directives/ref.js'
import { html, unsafeStatic } from 'lit/static-html.js'

@customElement('my-heading')
export class Heading extends ShallowLitElement {
  nodeViewContext = useNodeViewContext(this)

  override render() {
    const contentRef = this.nodeViewContext.value?.contentRef
    const node = this.nodeViewContext.value?.node
    if (!contentRef || !node)
      return
    const tag = `h${node.attrs.level}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
    return html`<${unsafeStatic(tag)} ${ref(contentRef)}></div>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'my-heading': Heading
  }
}

// examples/vue/components/Heading.vue
<script setup lang="ts">
import { useNodeViewContext } from '@prosemirror-adapter/vue'
import { computed } from 'vue'

const { contentRef, node } = useNodeViewContext()

const tag = computed(() => {
  return `h${node.value.attrs.level}`
})
</script>

<template>
  <component :is="tag" :ref="contentRef" />
</template>
