// examples/react/components/Heading.tsx
/* Copyright 2021, Prosemirror Adapter by Mirone. */
import { useNodeViewContext } from '@prosemirror-adapter/react'

export function Heading() {
  const { contentRef, node } = useNodeViewContext()
  const Tag = `h${node.attrs.level}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  return <Tag ref={contentRef} />
}

// examples/vue/components/Heading.vue
<script setup lang="ts">
import { useNodeViewContext } from '@prosemirror-adapter/vue'
import { computed } from 'vue'

const { contentRef, node } = useNodeViewContext()

const tag = computed(() => {
  return `h${node.value.attrs.level}`
})
</script>

<template>
  <component :is="tag" :ref="contentRef" />
</template>
