// examples/svelte/src/components/Paragraph.svelte
<script lang="ts">
  import { useNodeViewContext } from "@prosemirror-adapter/svelte";
  let selected = false;

  const contentRef = useNodeViewContext('contentRef');
  const selectedStore = useNodeViewContext('selected');
  selectedStore.subscribe((value) => {
    selected = value;
  })

</script>

<div use:contentRef class:selected={selected} ></div>

<style>
  .selected {
    outline: blue solid 1px;
  }
</style>

// examples/vue/components/Paragraph.vue
<script setup lang="ts">
import { useNodeViewContext } from '@prosemirror-adapter/vue';

const { contentRef, selected } = useNodeViewContext();
</script>

<template>
    <div role="presentation" :class="{ selected: selected }" :ref="contentRef"></div>
</template>

<style scoped>
.selected {
    outline: blue solid 1px;
}
</style>
