// examples/lit/src/components/Hashes.ts
import { ShallowLitElement, useWidgetViewContext } from '@prosemirror-adapter/lit'
import { html } from 'lit'
import { customElement } from 'lit/decorators.js'

@customElement('my-hashes')
export class Hashes extends ShallowLitElement {
  widgetViewContext = useWidgetViewContext(this)

  override render() {
    const spec = this.widgetViewContext.value?.spec
    const level = spec?.level ?? 0
    const hashes = Array(level).fill('#').join('')
    return html`<span class="hash">${hashes}</span>`
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'my-hashes': Hashes
  }
}

// examples/solid/src/components/Hashes.tsx
import { useWidgetViewContext } from "@prosemirror-adapter/solid";

export function Hashes() {
  const { spec } = useWidgetViewContext();
  const level = spec?.level;
  const hashes = new Array(level || 0).fill("#").join("");

  return <span style={{ color: "blue", "margin-right": "6px" }}>{hashes}</span>;
}
