// examples/vue/components/Paragraph.vue
<script setup lang="ts">
import { nodeViewContext } from '@prosemirror-adapter/vue';
import { inject } from 'vue';

const { contentRef, selected } = inject(nodeViewContext)!;
</script>

<template>
    <div role="presentation" :class="{ selected: selected }" :ref="contentRef"></div>
</template>

<style scoped>
.selected {
    outline: blue solid 1px;
}
</style>

// examples/react/components/Paragraph.tsx
/* Copyright 2021, Prosemirror Adapter by Mirone. */
import { nodeViewContext } from '@prosemirror-adapter/react';
import { useContext } from 'react';

export const Paragraph = () => {
    const { contentRef, selected } = useContext(nodeViewContext);
    return <div style={{ outline: selected ? 'blue solid 1px' : 'none' }} role="presentation" ref={contentRef} />;
};
